procedure aradesh02
begin
	gsay_reply(33, 111);
	giq_option(4, 33, 112, aradesh02_2, 50);
end

procedure aradesh02_2
begin
	if (local_var(1) >= 2) then begin
		call aradesh03();
	end
	else begin
		call aradesh08();
	end
end

procedure aradesh03
begin
	gsay_reply(33, 116);
	giq_option(4, 33, 117, aradesh04, 50);
	giq_option(4, 33, 118, aradesh01_2, 51);
	giq_option(5, 33, 119, aradesh07, 51);
	giq_option(4, 33, 120, aradesh07, 51);
end

procedure aradesh04
begin
	gsay_message(33, 121, 50);
	call aradeshend();
end

procedure aradeshend
begin
end
